version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vila_lab_app
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - vilalab

  webserver:
    image: nginx:latest
    container_name: vila_lab_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - vilalab

  db:
    image: mysql:8.0
    container_name: vila_lab_db
    restart: always
    environment:
      MYSQL_DATABASE: vila_lab
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: vila_lab
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - vilalab

networks:
  vilalab:

volumes:
  dbdata: